[package]
name = "gat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rust-ini = "0.17.0"
flate2 = "1.0.20"
sha1 = "0.6.0"
num-bigint = "0.4"
